services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: actexec
      MYSQL_DATABASE: act_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - '8765:80'
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
volumes:
  db_data:
