# INFO: ONLY USE THIS FOR DEVELOPMENT
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=actexec
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=act_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
